-- MySQL Script generated by MySQL Workbench
-- Sun Jan 11 11:41:13 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dindin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dindin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dindin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dindin` ;

-- -----------------------------------------------------
-- Table `dindin`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindin`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dindin`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dindin`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cooking_time` VARCHAR(255) NULL,
  `prep_time` VARCHAR(255) NULL,
  `serves` INT NULL,
  `cuisine` VARCHAR(255) NULL,
  `ingredients` TEXT NULL,
  `directions` TEXT NULL,
  `stars` INT NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipes_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_recipes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `dindin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
